Models/Auto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TIWP_APS_NET_FRAMEWORK_CORE.Models
{
	public class Auto
	{
		public string Marka { get; set; }
		public string Model { get; set; }

	}
}

Models/ErrorViewModel.cs
using System;

namespace TIWP_APS_NET_FRAMEWORK_CORE.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Controllers/CoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TIWP_APS_NET_FRAMEWORK_CORE.Controllers
{
    public class CoreController : Controller
    {
		public IActionResult Intro()
		{
			return View();
		}

		public IActionResult Pros()
		{
			return View();
		}

		public IActionResult Cons()
		{
			return View();
		}
	}
}

Controllers/FrameworkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace TIWP_APS_NET_FRAMEWORK_CORE.Controllers
{
	public class FrameworkController : Controller
	{
		public IActionResult Intro()
		{
			return View();
		}

		public IActionResult Pros()
		{
			return View();
		}

		public IActionResult Cons()
		{
			return View();
		}
	}
}

Controllers/RazorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TIWP_APS_NET_FRAMEWORK_CORE.Models;

namespace TIWP_APS_NET_FRAMEWORK_CORE.Controllers
{
    public class RazorController : Controller
	{
		public IActionResult Intro()
		{
			return View();
		}
		public IActionResult Intro2()
		{
			return View();
		}
		public IActionResult Intro3()
		{
			return View();
		}

		public IActionResult Dane()
		{
			return View();
		}
		public IActionResult Dane2()
		{
			return View();
		}

		public IActionResult Modele()
		{
			var model = new Auto()
			{
				Marka = "Volvo",
				Model = "V40"
			};
			
			//var model = new List<Auto>(){
			//	new Auto()
			//	{
			//		Marka = "Volvo",
			//		Model = "V40"
			//	},
			//	new Auto()
			//	{
			//		Marka = "Volvo 2 ",
			//		Model = "V4022"
			//	}
			//};

			return View(model);
		}
	}
}

Controllers/StartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TIWP_APS_NET_FRAMEWORK_CORE.Controllers
{
    public class StartController : Controller
	{
		public IActionResult Start()
		{
			return View();
		}
		public IActionResult Plan()
		{
			return View();
		}
	}
}

Controllers/SummaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TIWP_APS_NET_FRAMEWORK_CORE.Controllers
{
    public class SummaryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Core/Cons.cshtml
@{
	ViewData["Title"] = "Intro";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewData["Progres"] = 10;
}

<h3>Kiedy nie używać .NET Core...?</h3>

<span style="font-size: 15pt;">
	Jednym z problemów .NET Core jest brak wsparcia dla niektórych typów bibliotek w stosunku do .NET Framework. Warto mieć świadomość, kiedy nie będziemy mogli skorzystać z zalet tej technologii:
</span>

<br />
<br />

<ol style="font-size: 15pt;">
	<li>Windows Forms oraz WPF nie są wspierane. Jeżeli chcesz stowrzyć aplikację desktopową na system MacOS musisz posłużyć się zestawem narzędzi Mono;</li>
	<li>
		ASP.NET Web Forms również nie występują w .NET Core. Sama technologia .NET Framework wciąż jest wspierana oraz aktualizowana (nieco wolniej z uwagi na .NET Core)
		dlatego jeżeli chcesz używać tej technologii nie musisz niczego się obawiać;
	</li>
	<li>
		również usługi WCF zostały wycofane. Alternatywą jest REST API utworzone w technologii .NET Core. Ten typ projektu jest swojego rodzaju kontynuacją WCF - trzeba jednak mieć pełną świadomość zmiany niektórych konceptów.
	</li>
	<li>
		brak wsparcia bibliotek firm trzecich: na ten problem możecie natrafić, kiedy wasz przestarzały projekt będziecie przerabiać na technologię .NET Core.
	</li>
	<li>
		potrzebujesz dostępu do specyficznych API dla systemu Windows. .NET Core został zaprojektowany jako framework wieloplatformowy – może działać na każdym wspieranym systemie.
		Operacje takie jak dostęp do rejestru czy WMI (zestaw protokołów pozwalających na dostęp i zarządzanie zasobami komputera takimi jak adaptery sieciowe, lista procesów, czujniki temperatury, etc.)
		nie są dostępne z poziomu tej technologii.
	</li>
	<li>
		.NET Core jest stale rozwijana i oferuje coraz więcej. Znakomitym przykładem jest SignalR. Do wersji .NET Core 2.1 nie był wspierany.
	</li>

</ol>

Views/Core/Intro.cshtml
@{
	ViewData["Title"] = "Intro";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewData["Progres"] = 7;
}

<h3>Co to jest .NET Core?</h3>

<span style="font-size: 15pt;">
	ASP.NET Core to międzyplatformowa struktura typu open source o wysokiej wydajności służąca do tworzenia nowoczesnych aplikacji internetowych opartych na chmurze. Platforma ASP.NET Core umożliwia:
</span>
<br />

<ol style="font-size: 15pt;">
	<li>
		Kompilowanie aplikacji i usług internetowych, aplikacji IoT i zapleczy mobilnych.
	</li>
	<li>
		Używanie ulubionych narzędzi programistycznych w systemach Windows, macOS i Linux.
	</li>
	<li>
		ŚWdrażanie w chmurze lub lokalnie.
	</li>
	<li>
		Uruchamianie na platformie .NET Core lub .NET Framework.
	</li>
</ol>

Views/Core/Pros.cshtml
@{
	ViewData["Title"] = "Intro";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewData["Progres"] = 8;
}

<h3>Dlaczego warto korzystać z platformy ASP.NET Core?</h3>

<span style="font-size: 15pt;">
	Miliony deweloperów korzystają z platformy ASP.NET 4.x do tworzenia aplikacji internetowych. ASP.NET Core to przeprojektowana platforma ASP.NET 4.x, w której wprowadzono zmiany architektoniczne w celu stworzenia bardziej zwartej i modułowej struktury.

	<br />
	<br />
	ASP.NET Core zapewnia następujące korzyści:
</span>

<ol style="font-size: 15pt;">

	<li>Zunifikowany scenariusz tworzenia interfejsu API sieci Web i internetowych sieci Web.</li>
	<li>Zaprojektowane pod kątem testowania.</li>
	<li>Razor Pages sprawia, że kodowanie scenariuszy ukierunkowanych na strony jest łatwiejsze i bardziej produktywne.</li>
	<li>Blazor umożliwia korzystanie C# z przeglądarki obok JavaScript. Udostępnianie logiki aplikacji po stronie serwera i klienta, która jest zapisywana przy użyciu platformy .NET.</li>
	<li>Możliwość programowania i uruchamiania w systemach Windows, macOS i Linux.</li>
	<li>Otwarte i skoncentrowane na społeczności.</li>
	<li>Integracja nowoczesnych struktur po stronie klienta i przepływów pracy projektowania.</li>
	<li>Obsługa hostingu zdalnych wywołań procedur (RPC) za pomocą usługi gRPC.</li>
	<li>System konfiguracjioparty na środowisku, który jest gotowy do chmury.</li>
	<li>Wbudowane iniekcja zależności.</li>
	<li>Lekki, wysoko wydajnyi modularny potok żądań HTTP.</li>
	<li>Możliwość hostowania na np.: Kestrel, Apache, Docker</li>
</ol>

Views/Framework/Cons.cshtml
@{
	ViewData["Title"] = "Intro";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewData["Progres"] = 5;
}


<h3>Kiedy nie używać .NET Framework...?</h3>

<span style="font-size: 15pt;">
	Warto również wymienić kilka sytuacji w których nie warto kierować się wyborem technologii .NET Framework:
</span>
<br />
<br />
<ol style="font-size: 15pt;">
	<li>
		wymagane jest wsparcie różnych systemów operacyjnych;
	</li>
	<li>
		wymaga jest wysoka wydajność i skalowalność nowo powstających projektów;
	</li>
	<li>
		platforma .NET Core realizuje wszystkie nasze wymagania;
	</li>
	<li>
		wymagana jest struktra otwartego oprogramowania.
	</li>
</ol>

Views/Framework/Intro.cshtml
@{
	ViewData["Title"] = "Intro";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewData["Progres"] = 3;
}

<h3>Co to jest .NET Framework?</h3>

<span style="font-size: 15pt;">
	.NET Framework to zarządzane środowisko wykonawcze dla systemu Windows, które zapewnia różne usługi dla uruchomionych aplikacji.
	Składa się z dwóch głównych składników: środowiska uruchomieniowego języka wspólnego (CLR), który jest aparatem wykonywania obsługującym aplikacje działające i Biblioteka klas .NET Framework,
	która udostępnia bibliotekę przetestowanego kodu do wielokrotnego użytku, który deweloperzy mogą wywoływać z własnych aplikacji. Usługi zapewniane przez .NET Framework do uruchamiania aplikacji
	obejmują następujące elementy:
</span>
<br /><br />
<ol style="font-size: 15pt;">
	<li>
		Zarządzanie pamięcią. W wielu językach programowania programiści są odpowiedzialni za przydzielanie i zwalnianie pamięci i za obsługę czasów istnienia obiektów. W aplikacjach .NET Framework CLR
		udostępnia te usługi w imieniu aplikacji.
	</li>
	<li>
		Wspólny system typów. W tradycyjnych językach programowania typy podstawowe są definiowane przez kompilator, co komplikuje współdziałania wielu języków. W programie .NET Framework typy podstawowe
		są zdefiniowane przez system typów programu .NET Framework i wspólne dla wszystkich języków przeznaczonych dla środowiska .NET Framework.
	</li>
	<li>
		Kompleksowa biblioteka klas. Zamiast konieczności pisania ogromnych ilości kodu do obsługi typowych operacji programistycznych niskiego poziomu, programiści wykorzystują łatwo dostępną bibliotekę
		typów i ich członków z biblioteki klas .NET Framework.
	</li>
	<li>
		Środowiska i technologie programistyczne. .NET Framework obejmuje biblioteki dla określonych obszarów tworzenia aplikacji, takich jak ASP.NET for Web Apps, ADO.NET do uzyskiwania dostępu do danych,
		Windows Communication Foundation dla aplikacji opartych na usłudze i Windows Presentation Foundation dla aplikacji klasycznych systemu Windows.
	</li>
	<li>
		Przeznaczanie dla wielu platform. Według .NET Standard, deweloperzy tworzą biblioteki klas, które działają na wielu platformach .NET Framework obsługiwanych przez tę wersję Standard. Na przykład
		biblioteki przeznaczone dla .NET Standard 2,0 mogą być używane przez aplikacje obsługujące .NET Framework 4.6.1, .NET Core 2,0 i platformy UWP 10.0.16299.
	</li>
</ol>

Views/Framework/Pros.cshtml
@{
	ViewData["Title"] = "Intro";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewData["Progres"] = 4;
}

<h3>Kiedy używać .NET Framework...?</h3>

<span style="font-size: 15pt;">
	.NET Framework jest ściśle powiązany z systemem Windows. W głównej mierze używany jest do tworzenia aplikacji desktopowych oraz dużych aplikacji biznesowych.
	<br />
	<br />
	Argumenty przemawiające z użyciem tej technologii:
</span>
<br />
<br />
<ol style="font-size: 15pt;">
	<li>
		kiedy jest ona obecnie w użyciu: zamiast przeprowadzania migracji projektu na nową technologię można dokonać jego rozszerzenia. 
		Programiści mogą napisać nowe usługi przy użyciu ASP.NET Core.;
	</li>
	<li>
		kiedy Twój projekt używa zewnętrznych bibliotek niewspieranych przez .NET Core
	</li>
	<li>
		kiedy używasz technologii jeszcze niedostępnych w .NET Core:
		<ol>
			<li>
				ASP.NET Web Forms;
			</li>
			<li>
				ASP.NET Web Pages;
			</li>
			<li>
				usługi internetowe WCF;
			</li>
			<li>
				Windows Workflow Foundation;
			</li>
			<li>
				Workflow Services;
			</li>
			<li>WCF Data Services (znane również pod nazwą ADO.NET Data Services);</li>
		</ol>
	</li>
</ol>

Views/Razor/Dane.cshtml
@{
	ViewData["Title"] = "Dane";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewData["Progres"] = 17;
}

<h1>View Bag, ViewData, TempData w ASP.net MVC</h1>

<h3>ViewBag - przekazywanie danych z kontrolera do widoku.</h3>

W ASP.NET MVC mamy 3 możliwości przekazywania danych z kontrolera do widoku. ViewBag i ViewData są prawie identyczne natomiast TempData posiada dłuższy czas istnienia.

<h3>Cechy wspólne ViewBag i ViewData</h3>
Zarówno ViewBag jak i ViewData są to obiekty krótkotrwałe, tworzone są na czas otwarcia widoku, po kliknięciu linka do innego adresu url zostają skasowane.


<h3>Różnice ViewBag i ViewData:</h3>
<ol>
	<li>
		ViewData to kolekcja typu słownik (Dictionary) zawierająca typy object, dziedzicząca po klasie ViewDataDictionary, kluczami w tym słowniku są zmienne typu string,

	</li>
	<li>
		ViewData wymaga rzutowania dla typów złożonych oraz sprawdzania wartości null aby zapobiec błędom,

	</li>
	<li>
		ViewBag jest typu dynamic (C# 4.0) a więc można zmieniać typ zmiennej w dowolnym momencie i nie wymaga rzutowania jak ViewData.
	</li>
</ol>

<div class="row">
	<div class="col-6">
		<h4>Przykład ViewBag w kontrolerze:</h4>
<pre>
public ActionResult Login(string returnUrl)
{
    ViewBag.ReturnUrl = returnUrl;
    return View();
}
</pre>
		<h4>Odczyt wartości z ViewBag w widoku:</h4>
<pre>
@@ViewBag.ReturnUrl
</pre>
	</div>
	<div class="col-6">
		<h4>Przykład ViewData w kontrolerze:</h4>
<pre>
public ActionResult Login(string returnUrl)
{
    ViewData["ReturnUrl"] = returnUrl;
    return View();
}</pre>

		<h4>Odczyt wartości z ViewData w widoku:</h4>
<pre>
@@ViewData["ReturnUrl"]</pre>
	</div>
</div>

Views/Razor/Dane2.cshtml
@{
	ViewData["Title"] = "Dane";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewData["Progres"] = 20;
}


<h3>TempData</h3>
TempData w pozwala przekazywać dane pomiędzy obecnym i kolejnymi żądaniami HTTP, nie tylko jednym jak w przypadku ViewData i ViewBag. Dane z TempData są zapisywane w sesji, niesie to ze sobą pewne konsekwencje. Przeglądarka użytkownika może mieć wyłączone ciasteczka, przez co nie uda się przekazać danych z TempData. Możliwe jest również trzymanie sesji na serwerze jednak to rozwiązanie niesie ze sobą inny problem. W przypadku, gdy portal obsługuje więcej niż jeden fizyczny serwer, ruch jest dzielony w zależności od obciążenia konkretnego serwera. Może się zdarzyć, że użytkownik przy kolejnym żądaniu zostanie skierowany na inny serwer, który nie posiada zapisanej sesji. Jedynym słusznym rozwiązaniem w tym wypadku jest trzymanie sesji we wspólnej bazie danych. Dane sesji są w tym wypadku współdzielone pomiędzy serwerami.

<h3>Przykład TempData w kontrolerze:</h3>
<pre>
public ActionResult Login(string returnUrl)
{
    TempData["ReturnUrl"] = returnUrl;
    return View();
}</pre>
<h3>Odczyt wartości z ViewData w widoku:</h3>
<pre>@@TempData["ReturnUrl"]</pre>

Views/Razor/Intro.cshtml
@{
	ViewData["Title"] = "Intro";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewData["Progres"] = 11;
}

<h1>ASP .NET MVC – silnik renderujący Razor</h1>
<br />

<span style="font-size: 17pt">
	Widok jest nieodłącznym elementem aplikacji ASP .Net MVC czym byłby on jednak bez odwołań do kodu C#?
	<br />
	Począwszy od 3 wersji MVC wprowadzona została składnia Razor – silnik renderujący pozwalający nam na łatwe wprowadzanie elementów kodu aplikacji do plików HTML.
	Rozszerzenia plików mają teraz postać .cshtml i są znacznie czytelniejsze od wcześniej stosowanych .aspx
</span>

<img src="~/razor1.png" />

Views/Razor/Intro2.cshtml
@{
	ViewData["Title"] = "Intro";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewData["Progres"] = 13;
}

<h1>ASP .NET MVC – silnik renderujący Razor</h1>
<br />

<img src="~/razor2.png" />

Views/Razor/Intro3.cshtml
@{
	ViewData["Title"] = "Intro";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewData["Progres"] = 15;
}

<h1>ASP .NET MVC – silnik renderujący Razor</h1>
<br />

<img src="~/razor2.png" />

Views/Razor/Modele.cshtml
@model Auto

@{

	ViewData["Title"] = "Modele";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewData["Progres"] = 25;
}

<h1>Modele dały @Model.Marka @Model.Model</h1>













@*model List<Auto>

	@{

		ViewData["Title"] = "Modele";
		Layout = "~/Views/Shared/_Layout.cshtml";
	}

	@foreach (var item in Model)
	{
		<h1>Modele dały @item.Marka @item.Model</h1>
	}
*@

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>S9 - RAZOR</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
	<header>
		<nav class="better-nav navbar navbar-expand-sm navbar-toggleable-sm navbar-light better-bg-info border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand text-light" asp-area="" asp-controller="Start" asp-action="Start">RAZOR</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

					<ul class="navbar-nav flex-grow-1">

						<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Start" asp-action="Plan">Wstęp</a>
						</li>

						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								ASP.Net Framework
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdown">
								<a class="dropdown-item" asp-area="" asp-controller="Framework" asp-action="Intro">Wstęp</a>
								<a class="dropdown-item" asp-area="" asp-controller="Framework" asp-action="Pros">Kiedy używać</a>
								<a class="dropdown-item" asp-area="" asp-controller="Framework" asp-action="Cons">Kiedy nie używać</a>
								<a class="dropdown-item" asp-area="" asp-controller="Framework" asp-action="XXX">TODO</a>
							</div>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								ASP.Net Core
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdown">
								<a class="dropdown-item" asp-area="" asp-controller="Core" asp-action="Intro">Wstęp</a>
								<a class="dropdown-item" asp-area="" asp-controller="Core" asp-action="Pros">Kiedy używać</a>
								<a class="dropdown-item" asp-area="" asp-controller="Core" asp-action="Cons">Kiedy nie używać</a>
								<a class="dropdown-item" asp-area="" asp-controller="Core" asp-action="XXX">TODO</a>
							</div>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Razor
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdown">
								<a class="dropdown-item" asp-area="" asp-controller="Razor" asp-action="Intro">Wstęp</a>
								<a class="dropdown-item" asp-area="" asp-controller="Razor" asp-action="Intro2">Razor part 2</a>
								<a class="dropdown-item" asp-area="" asp-controller="Razor" asp-action="Intro3">Razor part 3</a>
								<a class="dropdown-item" asp-area="" asp-controller="Razor" asp-action="Dane">Razor dane</a>
								<a class="dropdown-item" asp-area="" asp-controller="Razor" asp-action="Dane2">Razor dane part 2</a>
								<a class="dropdown-item" asp-area="" asp-controller="Razor" asp-action="Modele">Razor modele</a>
								<a class="dropdown-item" asp-area="" asp-controller="Razor" asp-action="XXX">TODO</a>
							</div>
						</li>
						<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Summary" asp-action="Index">Podsumowanie</a>
						</li>
					</ul>
				</div>

			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer">
		<div class="container">

			<div class="progress mt-1" style="height:20px;">
				<div class="progress-bar bg-success progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="@(ViewData["Progres"])" aria-valuemin="0" aria-valuemax="100" style="width: @(ViewData["Progres"])%">@(ViewData["Progres"])%</div>
			</div>

			&copy; 2019 - Sekcja 9 Razor (Core + Framework)
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>

Views/Start/Plan.cshtml
@{
	ViewData["Title"] = "Plan";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewData["Progres"] = 2;
}
<div style="font-size: 30pt; font-weight: 600;margin-top:75px">
	<div class="row">
		<div class="col-4 text-right">
			1.
		</div>
		<div class="col-8">
			Wstęp
		</div>
	</div>

	<div class="row">
		<div class="col-4 text-right">
			2.
		</div>
		<div class="col-8">
			ASP.Net Framework
		</div>
	</div>

	<div class="row">
		<div class="col-4 text-right">
			3.
		</div>
		<div class="col-8">
			ASP.Net Core
		</div>
	</div>

	<div class="row">
		<div class="col-4 text-right">
			4.
		</div>
		<div class="col-8">
			Razor
		</div>
	</div>

	<div class="row">
		<div class="col-4 text-right">
			5.
		</div>
		<div class="col-8">
			Podsumowanie
		</div>
	</div>
</div>

Views/Start/Start.cshtml
@{
	ViewData["Title"] = "Start";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewData["Progres"] = 1;
}
<br />
<br />
<div class="row col-12 mt-3">
	<div class="col-12 text-center">
		<h1>RAZOR (Framework + Core)</h1>
	</div>
</div>


<div class="row col-offset-8 col-4 mt-3 team-bottom">
	<div class="row col-12">
		<h3>Sekcja 9</h3>
	</div>
	<div class="row col-12">
		<h3><i>Jan Snopek</i></h3>
	</div>
	<div class="row col-12">
		<h3><i>Alan Biegun</i></h3>
	</div>
</div>

<img style="position:fixed;top: 20%; left: 75px; width: 25%;" src="~/meme1.png" />
<img style="position:fixed;top: 60%; left: 175px; width: 25%;" src="~/meme2.png" />

Views/Summary/Index.cshtml
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewData["Progres"] = 100;
}

<h1>Podsumowanie</h1>



Doszliśmy do wniosku, że każda z technologii ma swoje plusy i minusy, ograniczenia i zalety oraz odmienną charakterystkę.
<br />
Najlepszym podsumowaniem będzie sięgnięcie po informacje do źródła, firmy Microsoft:.NET Framework vs .NET Core
<br />
<br />
<img style="width:400px" src="~/meme3.png" />
<img src="~/summary.png" />


<br />
<br />
<b>.NET Framework</b> jest dojrzałą platformą dystrubuowaną z systemem Windows. Używaj tej technologii, gdy chcesz tworzyć aplikacje desktopowe i UWP lub jeżeli nie masz nic przeciwko pracy ze starszą technologią ASP.NET.

<br />
<br />
<b>.NET Core</b> jest technologią wieloplatformową działającą na systemach Windows, Linux oraz MacOS. Używaj tej technologii jeżeli chesz tworzyć aplikacje konsolowe lub internetowe, które będą działać na każdej z powyższych platform. Wysoka wydajność i skalowalność będzie osiągnięta przy wykorzystaniu konteneryzacji. Platforma ta jednak nie wspiera tworzenia aplikacji desktopowych oraz UWP.